version: '3.9'

services:
  db:
    image: postgres
    container_name: 'finances-db'
    environment:
      restart: never
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: 'fin-api'
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    container_name: 'finances-backend'
    build: .
    command: yarn dev
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - .:/src/app/finances-backend
      - /src/app/finances-backend/node_modules
    links:
      - db
    depends_on:
      - db
volumes:
  pgdata:
    driver: local
